apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
