apiVersion: v1
kind: Secret
metadata:
  name: mongo-sec
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.secrets.username | b64enc }}
  password: {{ .Values.secrets.password | b64enc }}
