apiVersion: v1
kind: Secret
metadata:
  name: mongo-sec
  namespace: three-tier
type: Opaque
stringData:
  username: admin
  password: password123
  mongo-url: mongodb://admin:password123@mongodb.three-tier.svc.cluster.local:27017/admin?authSource=admin
