apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: YWRtaW4=        # admin
  password: cGFzc3dvcmQxMjM= # password123
