namespace: three-tier

image:
  repository: mongo
  tag: "4.4.6"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 27017

persistence:
  enabled: true
  storageClass: gp2
  size: 1Gi

auth:
  enabled: true
  rootUser: admin
  rootPassword: admin123
  database: appdb
  username: appuser
  password: app123
