apiVersion: v1
kind: Secret
metadata:
  name: mongo-sec
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  mongo-url: mongodb://admin:password123@mongodb-svc.three-tier.svc.cluster.local:27017/todo?authSource=admin
