{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: {{ .Values.namespace }}
  annotations:
{{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.paths.frontend.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.paths.frontend.serviceName }}
                port:
                  number: {{ .Values.ingress.paths.frontend.servicePort }}

          - path: {{ .Values.ingress.paths.backend.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.paths.backend.serviceName }}
                port:
                  number: {{ .Values.ingress.paths.backend.servicePort }}
{{- end }}
