namespace: three-tier

replicaCount: 1

image:
  repository: 767828733016.dkr.ecr.ap-south-1.amazonaws.com/frontend
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: ecr-registry-secret

service:
  type: ClusterIP
  port: 80   # IMPORTANT: frontend must expose 80 (nginx)

ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  paths:
    frontend:
      path: /
      serviceName: frontend
      servicePort: 80
    backend:
      path: /api
      serviceName: api
      servicePort: 3500

env:
  backendUrl: "/api"   # frontend talks to backend via ingress

resources: {}
